### PR TITLE
re-work of spatial APIs

### PR DESCRIPTION
**Pull request by noisyboiler**
**breaking** changes from initial "beta" release

- re-implement `create_geometry`
- stop `delete` APIs actually deleting peoples application Nodes - only remove relationship to spatial index
- refactor APIs to respect GIS standards
- *breaking* signature changes to APIs for consistency going forward
- massive clarification on documentation
- new API to find interesting geometries from a given location
- new API to find the geometries that contain a POI
- huge increase in test coverage
- no longer match on WKT strings to avoid rounding precision bugs
- geometry names only need be unique across a single Layer
- return upstream API HTTP responses instead of Node instances on CRUD operations

### CODE REVIEW

**Comment by nigelsmall** [comment]
@noisyboiler Does this still need merging?

**Comment by noisyboiler** [comment]
Hey Nigel. Going to dump the "raw" responses in favour of graph json. Will do this over the weekend, then yes please.

**Comment by nigelsmall** [comment]
OK, I'm going to release 2.0.8 today so we can push this to 2.0.9.

**Comment by noisyboiler** [comment]
@nigelsmall good to go in the next release

**Comment by nigelsmall** [comment]
@noisyboiler - can you re-raise against the 2.1.0 branch?

**Comment by noisyboiler** [comment]
re-raising against 2.1.0

**Pull request closed without merging**
